import type { PinFieldProfileConfig } from "@/lib/pin-field/types";
import { palette } from "@/config/colors";

const sharedLighting = {
  ambientIntensity: 0.78,
  hemisphereIntensity: 0.95,
  keyLightIntensity: 2.35,
  fillLightIntensity: 1.1,
  rimLightIntensity: 1.45,
  accentLightIntensity: 0.85,
  groundLightIntensity: 0.55,
} as const;

export const pinFieldLabProfile: PinFieldProfileConfig = {
  id: "lab",
  gridSize: 64,
  spacing: 0.2,
  pinRadius: 0.1,
  pinCapSegments: 1,
  pinRadialSegments: 12,
  maxHeight: 0.55,
  minHeight: 0.06,
  influenceRadius: 1.65,
  heightLerp: 0.14,
  mouseLerp: 0.18,
  pinColor: "#d4d4d8",
  pinColorPressed: "#38bdf8",
  baseColor: "#141417",
  groundColor: "#34343a",
  materialMetalness: 0.38,
  materialRoughness: 0.5,
  wave: {
    amplitude: 0.14,
    speed: 3.15,
    frequencyX: 1.05,
    frequencyZ: 0.82,
    crossMix: 0.38,
  },
  lighting: { ...sharedLighting },
  camera: {
    position: [-3, 3, 3],
    lookAt: [0, -1, 0],
    fov: 42,
    near: 0.1,
    far: 30,
  },
  fog: { near: 14, far: 26 },
  dpr: [1, 2],
};

export const pinFieldHeroProfile: PinFieldProfileConfig = {
  id: "hero",
  gridSize: 72,
  gridSizeMd: 48,
  gridSizeSm: 38,
  spacing: 0.2,
  pinRadius: 0.1,
  pinCapSegments: 4,
  pinRadialSegments: 10,
  maxHeight: 0.7,
  minHeight: 0.08,
  influenceRadius: 2,
  heightLerp: 0.14,
  mouseLerp: 0.18,
  pinColor: palette.hero.pin,
  pinColorPressed: palette.hero.pinPressed,
  surfaceColor: palette.hero.pin,
  baseColor: palette.hero.sceneBackground,
  groundColor: palette.hero.pin,
  materialMetalness: 0,
  materialRoughness: 0.5,
  wave: {
    amplitude: 0.3,
    speed: 2,
    frequencyX: 0.95,
    frequencyZ: 0.75,
    crossMix: 0.32,
  },
  lighting: {
    ambientIntensity: 1,
    hemisphereIntensity: 1.25,
    keyLightIntensity: 2.75,
    fillLightIntensity: 1.15,
    rimLightIntensity: 0.7,
    accentLightIntensity: 0.55,
    groundLightIntensity: 0.45,
    skyColor: palette.three.sky,
    hemisphereGroundColor: palette.three.hemisphereGround,
    keyLightColor: palette.three.key,
    fillLightColor: palette.three.fill,
    rimLightColor: palette.three.rim,
    accentLightColor: palette.three.accent,
    groundLightColor: palette.three.ground,
    keyLightPosition: [4, 15, 7],
  },
  camera: {
    position: [-2.2, 3.8, 5.2],
    lookAt: [0, -1.15, 0],
    fov: 38,
    near: 0.1,
    far: 28,
  },
  cameraIntro: {
    startFactor: 0.28,
    durationMs: 1400,
  },
  fog: { near: 18, far: 36 },
  dpr: [1, 1.5],
};
