import type { ProjectRecord } from "@/lib/projects/types";

export const projects: ProjectRecord[] = [
  {
    id: "soulutions",
    name: "Soulutions",
    client: "Confidencial",
    role: "Web Desarrollador Full Stack",
    projectType: "Plataforma SaaS / Crowdfunding",
    involvement: "Estabilización de proyecto heredado + nuevas funcionalidades",
    featured: true,
    featuredLayout: "left",
    bentoLayout: { colSpan: 8, rowSpan: 5, coverRatio: "fill" },
    bentoLayoutMd: { colSpan: 4, rowSpan: 4, coverRatio: "fill" },
    summary:
      "Plataforma de crowdfunding que conecta donantes con organizaciones de impacto, con seguimiento de hitos y métricas ODS.",
    description:
      "Soulutions (antes Gaia Gives) es una plataforma full-stack para conectar donantes con organizaciones y proyectos de impacto global. Integra hitos financieros, métricas de Objetivos de Desarrollo Sostenible (ODS) y un marketplace de recompensas para garantizar transparencia en el uso de los fondos.",
    stackPrimary: ["Remix", "TypeScript", "Prisma", "Stripe"],
    stack: [
      "Remix",
      "React",
      "TypeScript",
      "MySQL",
      "Prisma",
      "Tailwind CSS",
      "Firebase",
      "Stripe",
      "Cloudinary",
    ],
    highlights: [
      "Recuperé un proyecto heredado sin credenciales ni documentación.",
      "Integré Stripe para donaciones únicas y recurrentes.",
      "Entregué el marco ODS bajo plazos muy exigentes.",
    ],
    contributions: [
      "Integración completa con Stripe para pagos únicos y mensuales.",
      "Implementación del marco de Objetivos de Desarrollo Sostenible (ODS).",
      "Marketplace para canje de puntos karma y soporte para Go High Level.",
      "Corrección de shortlinks, login inseguro y cálculo de puntos.",
      "Rediseño y retrabajo de múltiples rutas críticas del producto.",
    ],
    cover: {
      src: "/media/projects/soulutions-cover.svg",
      alt: "Vista previa del proyecto Soulutions",
    },
    gallery: [],
  },
  {
    id: "conta-fast",
    name: "Conta Fast",
    client: "Tavuel (interno)",
    role: "Web Desarrollador Full Stack",
    projectType: "SaaS contable y facturación electrónica",
    involvement: "Modernización de sistema legacy",
    featured: true,
    featuredLayout: "right",
    bentoLayout: { colSpan: 4, rowSpan: 4, coverRatio: "fill" },
    bentoLayoutMd: { colSpan: 2, rowSpan: 3, coverRatio: "fill" },
    summary:
      "Cliente web de contabilidad y facturación electrónica para Costa Rica, con cumplimiento tributario y gestión financiera multi-sucursal.",
    description:
      "Conta Fast es el cliente web de una plataforma SaaS de contabilidad y facturación electrónica diseñada para el mercado costarricense. Integra cumplimiento con Hacienda (ATV), catálogo CABYS, reportes tributarios y administración granular de usuarios y sucursales.",
    stackPrimary: ["React", "GraphQL", "MUI", "Firebase"],
    stack: [
      "React 18",
      "React Router",
      "Apollo Client",
      "GraphQL",
      "Material UI",
      "Firebase",
      "Recharts",
      "jsPDF",
      "Sass",
    ],
    highlights: [
      "Migré por completo el stack del proyecto más antiguo de la empresa.",
      "Adapté la plataforma a nuevas normativas fiscales de Costa Rica.",
      "Rediseñé el módulo de facturación para cumplimiento legal vigente.",
    ],
    contributions: [
      "Actualización integral del stack tecnológico legacy.",
      "Nuevas funcionalidades derivadas de normativas de Hacienda (Tribu-CR).",
      "Rediseño del módulo de facturación electrónica y reportes tributarios.",
      "Correcciones de roles, responsividad y validaciones de negocio.",
    ],
    cover: {
      src: "/media/projects/conta-fast-cover.svg",
      alt: "Vista previa del proyecto Conta Fast",
    },
    gallery: [],
  },
  {
    id: "eurek-tickets",
    name: "Eurek Tickets",
    client: "Eureka Ticket",
    role: "Full Stack / Líder técnico",
    projectType: "SaaS de eventos y venta de tiquetes",
    involvement: "Desarrollo y liderazgo desde cero",
    featured: true,
    featuredLayout: "left",
    bentoLayout: { colSpan: 4, rowSpan: 5, coverRatio: "fill" },
    bentoLayoutMd: { colSpan: 2, rowSpan: 3, coverRatio: "fill" },
    summary:
      "Ecosistema SaaS para gestión de eventos y venta de tiquetes en Costa Rica, con pagos SINPE, control de acceso QR y panel administrativo.",
    description:
      "EurekaTicket es una solución full-stack para eventos físicos y digitales con arquitectura multi-tenant. Incluye administración de eventos, venta de boletos, red de vendedores, check-in con QR y reportes municipales adaptados al mercado local.",
    stackPrimary: ["Node.js", "GraphQL", "React", "Prisma"],
    stack: [
      "Node.js",
      "TypeScript",
      "GraphQL",
      "Apollo Server",
      "React",
      "Vite",
      "Prisma",
      "MySQL",
      "Docker",
      "Firebase",
      "Tailwind CSS",
    ],
    highlights: [
      "Lideré el producto SaaS de principio a fin.",
      "Definí arquitectura backend, frontends e infraestructura.",
      "Mentoricé desarrolladores mediante code reviews y capacitación.",
    ],
    contributions: [
      "Diseño e implementación del backend modular con GraphQL y Prisma.",
      "Dos frontends: panel administrativo y app para compradores (PWA).",
      "Pasarela flexible con efectivo, tarjeta, transferencia y SINPE.",
      "Optimización con DataLoader, roles granulares y trazabilidad de boletos.",
    ],
    cover: {
      src: "/media/projects/eurek-tickets-cover.svg",
      alt: "Vista previa del proyecto Eurek Tickets",
    },
    gallery: [],
  },
  {
    id: "tecno-air-landing",
    name: "Tecno Air Cold",
    client: "Tecno Air Cold",
    role: "Web Desarrollador Full Stack",
    projectType: "Landing page corporativa HVAC",
    involvement: "Desarrollo desde cero",
    featured: false,
    bentoLayout: { colSpan: 3, rowSpan: 4, coverRatio: "fill" },
    bentoLayoutMd: { colSpan: 2, rowSpan: 3, coverRatio: "fill" },
    summary:
      "Landing corporativa con Angular SSR para una empresa HVAC, orientada a SEO, portafolio de proyectos y captación de clientes.",
    description:
      "Aplicación web tipo landing page para climatización, refrigeración y aire acondicionado. Incluye servicios, portafolio de proyectos, reseñas, equipo y contacto, con arquitectura SSR para rendimiento y posicionamiento.",
    stackPrimary: ["Angular 19", "SSR", "Firebase", "TypeScript"],
    stack: [
      "Angular 19",
      "Angular SSR",
      "Express",
      "Angular Material",
      "SCSS",
      "Swiper.js",
      "Firebase",
      "TypeScript",
    ],
    highlights: [
      "Entrega completa en una semana o menos.",
      "Arquitectura SSR optimizada para SEO desde el inicio.",
      "Diseño responsivo con identidad visual de la marca.",
    ],
    contributions: [
      "Desarrollo completo de todas las secciones del sitio.",
      "Implementación de Angular SSR con servidor Express.",
      "Configuración de despliegue en Firebase e iconografía SVG personalizada.",
    ],
    cover: {
      src: "/media/projects/tecno-air-landing-cover.svg",
      alt: "Vista previa del landing Tecno Air Cold",
    },
    gallery: [],
  },
  {
    id: "tecno-air-fsm",
    name: "Tecno Air Cold FSM",
    client: "Tecno Air Cold",
    role: "Web Desarrollador Full Stack",
    projectType: "Field Service Management",
    involvement: "Mantenimiento y nuevas funcionalidades",
    featured: false,
    bentoLayout: { colSpan: 5, rowSpan: 4, coverRatio: "fill" },
    bentoLayoutMd: { colSpan: 2, rowSpan: 3, coverRatio: "fill" },
    summary:
      "Sistema de gestión de servicios de campo para operaciones HVAC: clientes, activos, reportes técnicos y control de horas.",
    description:
      "Plataforma FSM que conecta administración con trabajo técnico en sitio. Permite gestionar clientes, activos, reportes de mantenimiento, programación de técnicos y generación automática de PDFs para clientes.",
    stackPrimary: ["Angular 15", "NGXS", "Firebase", "TypeScript"],
    stack: [
      "Angular 15",
      "TypeScript",
      "Angular Material",
      "NGXS",
      "Firebase",
      "Firestore",
      "Cloud Functions",
      "jsPDF",
      "LESS",
    ],
    highlights: [
      "Mantuve estable un sistema crítico para la operación diaria del cliente.",
      "Amplié reportes técnicos y control de horas según nuevas necesidades.",
    ],
    contributions: [
      "Mantenimiento general del sistema en producción.",
      "Implementación y corrección de funcionalidades pendientes del cliente.",
    ],
    cover: {
      src: "/media/projects/tecno-air-fsm-cover.svg",
      alt: "Vista previa del sistema FSM Tecno Air Cold",
    },
    gallery: [],
  },
  {
    id: "king-of-kings",
    name: "King of Kings",
    client: "King of Kings",
    role: "Web Desarrollador Full Stack",
    projectType: "Ecosistema de reservas para barbería",
    involvement: "Mantenimiento y nuevas funcionalidades",
    featured: false,
    bentoLayout: { colSpan: 5, rowSpan: 3, coverRatio: "fill" },
    bentoLayoutMd: { colSpan: 2, rowSpan: 2, coverRatio: "fill" },
    summary:
      "Ecosistema de tres apps para reservas de barbería: cliente PWA, panel administrativo y API centralizada con agenda en tiempo real.",
    description:
      "Solución digital 360° para reservas autónomas de clientes y gestión interna de agenda, personal e inventario. Incluye notificaciones, analítica de marketing y despliegue en AWS y Firebase.",
    stackPrimary: ["GraphQL", "React", "Node.js", "AWS"],
    stack: [
      "Node.js",
      "GraphQL",
      "TypeScript",
      "Prisma",
      "MySQL",
      "React 18",
      "Vite",
      "Material UI",
      "Firebase",
      "AWS ECS",
      "Docker",
      "FullCalendar",
    ],
    highlights: [
      "Sostuve en producción un ecosistema de tres aplicaciones interconectadas.",
      "Resolví bugs críticos en horarios disponibles y excepciones de agenda.",
    ],
    contributions: [
      "Mantenimiento del ecosistema cliente, admin y API.",
      "Corrección de bugs en agendamiento y nuevas funcionalidades solicitadas.",
    ],
    cover: {
      src: "/media/projects/king-of-kings-cover.svg",
      alt: "Vista previa del ecosistema King of Kings",
    },
    gallery: [],
  },
];

export const featuredProjects = projects.filter((project) => project.featured);

export function getProjectById(id: string) {
  return projects.find((project) => project.id === id);
}
